"""Build an isolated, rights-filtered Poki project and reproducible submission ZIP.

The full product config/catalog/artwork is never replaced during this build.
"""
import argparse
import gzip
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "tools/release"))
from catalog_pipeline_lib.pipeline import lock
from inspect_pack import inspect
from catalog import projection

SDK_URL = "https://game-cdn.poki.com/scripts/v2/poki-sdk.js"


def dump(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def prepare(output, qa=False):
    stage = output / ("project-qa" if qa else "project-production")
    if stage.exists():
        if not (stage / ".pieceful-poki-generated").is_file():
            raise ValueError("Refusing to replace an unowned staging directory")
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    (stage / ".pieceful-poki-generated").write_text("Generated by tools/poki/build.py\n")
    view = projection()
    for folder in ("scripts", "assets", "cut_patterns", "content", "licenses", "addons/catalog_source_export", "poki"):
        for source in sorted((ROOT / folder).rglob("*")):
            if not source.is_file() or source.is_symlink():
                continue
            relative = source.relative_to(ROOT)
            name = relative.as_posix()
            if name.startswith("assets/demo_") or name.startswith("poki/web/"):
                continue
            target = stage / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
    # The frozen base class preloads its historical fallback. The Poki board
    # always selects approved museum art before building pieces. Substitute a
    # generated plain-paper fallback ONLY in staging; none of the three
    # unapproved original SVG bytes is delivered or counted as release art.
    (stage / "assets/demo_garden.svg").write_text('<svg xmlns="http://www.w3.org/2000/svg" width="960" height="600"><rect width="960" height="600" fill="#fafaf5"/></svg>\n')
    dump(stage / "content/catalog_v1.json", view["catalog"])
    dump(stage / "content/curation/catalog_identity_manifest_v1.json", view["identity"])
    dump(stage / "poki/themes.json", view["manifest"]["themes"])
    dump(stage / "poki/artwork_manifest.json", view["manifest"])
    inventory = json.loads((ROOT / "licenses/ASSET_MANIFEST.json").read_text())
    ids = set(view["profile"]["artwork_ids"])
    inventory["artworks"] = [r for r in inventory["artworks"] if r["id"] in ids]
    inventory["poki_profile_note"] = "Original SVG fixtures omitted; base fallback is generated plain paper, not catalog artwork. Unresolved project/native obligations remain unresolved."
    dump(stage / "licenses/ASSET_MANIFEST.json", inventory)
    project = (ROOT / "project.godot").read_text().replace('config/name="Piecepace: Jigsaw Puzzles"', 'config/name="Pieceful-Poki-RC1"')
    project = project.replace('run/main_scene="res://main.tscn"', 'run/main_scene="res://poki/main.tscn"')
    (stage / "project.godot").write_text(project)
    (stage / "export_presets.cfg").write_bytes((ROOT / "poki/export_presets.cfg").read_bytes())
    if qa:
        for source in (ROOT / "tests").glob("poki_*"):
            shutil.copy2(source, stage / source.name)
        # The existing control/renderer probe is QA-only and unchanged.
        shutil.copy2(ROOT / "tests/commercial_product_browser_fixture.gd", stage / "commercial_product_browser_fixture.gd")
        scene = (stage / "poki/main.tscn").read_text().replace('load_steps=7', 'load_steps=9')
        scene = scene.replace('[node name="Main"', '[ext_resource type="Script" path="res://commercial_product_browser_fixture.gd" id="7_probe"]\n[ext_resource type="Script" path="res://poki_browser_probe.gd" id="8_probe"]\n\n[node name="Main"', 1)
        scene += '\n[node name="ExistingQaProbe" type="Node" parent="."]\nscript = ExtResource("7_probe")\n\n[node name="PokiQaProbe" type="Node" parent="."]\nscript = ExtResource("8_probe")\n'
        (stage / "poki/main.tscn").write_text(scene)
    return stage, view


def build(output, godot, qa=False, prepare_only=False):
    output = output.resolve()
    if not output.is_relative_to(ROOT / "build") or output == ROOT / "build":
        raise ValueError("Use an isolated directory below repository build/")
    output.mkdir(parents=True, exist_ok=True)
    (ROOT / "build/.gdignore").touch()
    with lock(ROOT):
        stage, view = prepare(output, qa)
        if prepare_only:
            print(stage)
            return
        destination = output / ("qa" if qa else "production")
        if destination.exists():
            permitted = {"poki_bridge.js", "artwork-manifest.json", "provenance.json", "hash-manifest.json"}
            if qa:
                permitted.add("poki_qa_stub.js")
            if any(not p.is_file() or (not p.name.startswith("index.") and p.name not in permitted)
                   for p in destination.iterdir()):
                raise ValueError("Refusing to replace unexpected files in the export directory")
            for p in destination.iterdir():
                p.unlink()
        destination.mkdir(exist_ok=True)
        subprocess.run([godot, "--headless", "--path", str(stage), "--editor", "--quit"], check=True)
        subprocess.run([godot, "--headless", "--path", str(stage), "--export-release", "Web Poki", str(destination / "index.html")], check=True)
        subprocess.run([sys.executable, str(ROOT / "tools/instrument_web_loader.py"), str(destination / "index.html")], check=True)
        for sidecar in destination.glob("index.*.import"):
            sidecar.unlink()
        html = destination / "index.html"
        inject = ('<script>window.__PIECEFUL_POKI_QA__=true;</script>\n<script src="poki_qa_stub.js"></script>' if qa
                  else f'<script src="{SDK_URL}"></script>')
        html.write_text(html.read_text().replace('</head>', inject + '\n<script src="poki_bridge.js"></script>\n</head>', 1))
        shutil.copy2(ROOT / "poki/web/poki_bridge.js", destination / "poki_bridge.js")
        if qa:
            shutil.copy2(ROOT / "tests/poki_qa_stub.js", destination / "poki_qa_stub.js")
        dump(destination / "artwork-manifest.json", view["manifest"])
        revision = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
        dirty = bool(subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True).strip())
        provenance = {"profile": view["profile"]["profile"], "source_sha": revision,
                      "source_dirty": dirty, "qa": qa, "engine": subprocess.check_output([godot, "--version"], text=True).strip(),
                      "official_sdk_url": SDK_URL, "save_namespace": view["profile"]["save_namespace"]}
        dump(destination / "provenance.json", provenance)
        if not qa:
            report = inspect(destination / "index.pck", stage)
            if report["catalog_identity"]["original_byte_hashes_verified"] < 30:
                raise ValueError("Insufficient packaged catalog")
            dump(output / "pack-inspection.json", report)
        files = [{"path": p.name, "bytes": p.stat().st_size, "sha256": hashlib.sha256(p.read_bytes()).hexdigest(),
                  "calculated_gzip_bytes": len(gzip.compress(p.read_bytes(), mtime=0))}
                 for p in sorted(destination.iterdir()) if p.is_file() and p.name != "hash-manifest.json"]
        dump(destination / "hash-manifest.json", {"algorithm": "SHA256", "files": files,
             "note": "Manifest excludes itself; compression values are calculated, not CDN transfers."})
        manifest = destination / "hash-manifest.json"
        files.append({"path": manifest.name, "bytes": manifest.stat().st_size,
                      "sha256": hashlib.sha256(manifest.read_bytes()).hexdigest(),
                      "calculated_gzip_bytes": len(gzip.compress(manifest.read_bytes(), mtime=0))})
        dump(output / ("qa-metrics.json" if qa else "production-metrics.json"),
             {"build": provenance, "files": files, "raw_bytes": sum(f["bytes"] for f in files),
              "calculated_gzip_bytes": sum(f["calculated_gzip_bytes"] for f in files)})
        if not qa:
            archive = output / "PIECEFUL_POKI_RC1.zip"
            with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zipped:
                for p in sorted(destination.iterdir()):
                    if p.is_file():
                        info = zipfile.ZipInfo(p.name, date_time=(2026, 1, 1, 0, 0, 0))
                        info.compress_type = zipfile.ZIP_DEFLATED
                        info.external_attr = 0o100644 << 16
                        zipped.writestr(info, p.read_bytes(), compresslevel=9)
            print(json.dumps({"zip": str(archive), "zip_bytes": archive.stat().st_size,
                              "distinct_artworks": len(view["catalog"]["contents"]), "source_dirty": dirty}))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "build/poki-rc1")
    parser.add_argument("--godot", default=os.environ.get("GODOT_BIN", "godot"))
    parser.add_argument("--qa", action="store_true")
    parser.add_argument("--prepare-only", action="store_true")
    args = parser.parse_args()
    build(args.output, args.godot, args.qa, args.prepare_only)
